FROM cloudflare/cloudflared:latest

# Set the timezone
# RUN ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

# RUN cat /etc/os-release

# RUN source ~/.bashrc

# RUN tunnel --no-autoupdate run --token $TOKEN

# ENV TOKEN=""

CMD ["tunnel", "--no-autoupdate", "run", "--token", "$TOKEN"]